export const BASIC_BRAZILIAN_RECIPE_SLUGS = [
  "feijao-caseiro",
  "arroz-branco",
  "macarrao-alho-e-oleo",
  "macarrao-molho-branco",
  "macarrao-molho-de-queijo",
  "pure-de-batata",
  "frango-grelhado",
  "omelete-simples",
  "strogonoff-de-frango",
  "panqueca-simples",
  "farofa-simples",
  "bolo-simples",
  "cuscuz-simples",
  "tapioca-simples",
  "molho-de-tomate-caseiro",
  "carne-moida-refogada",
  "escondidinho-simples",
  "fricasse-de-frango",
  "lasanha-simples",
] as const;
