import type { Recipe } from "@/features/recipes/types";

export const LIBRARY_RECIPES: Recipe[] = [
  {
    id: "library-macarrao-alho-e-oleo",
    title: "Macarrao alho e oleo",
    description: "Classico rapido com alho dourado e toque de salsinha.",
    ingredients: ["macarrao", "alho", "azeite", "sal", "salsinha"],
    steps: [
      "Cozinhe o macarrão em água com sal até ficar al dente.",
      "Doure o alho fatiado em azeite, sem queimar.",
      "Misture o macarrao escorrido e finalize com salsinha picada.",
    ],
    prepMinutes: 20,
    servings: 2,
    sourceLabel: "TudoGostoso",
    origin: "library",
  },
  {
    id: "library-omelete-cremosa",
    title: "Omelete cremosa de frigideira",
    description: "Ovos bem batidos com queijo derretido e ervas.",
    ingredients: ["ovo", "leite", "queijo", "sal", "pimenta", "cebolinha"],
    steps: [
      "Bata ovos com leite, sal e pimenta.",
      "Despeje em frigideira untada e cozinhe em fogo baixo.",
      "Adicione queijo e cebolinha antes de dobrar.",
    ],
    prepMinutes: 12,
    servings: 1,
    sourceLabel: "Panelinha",
    origin: "library",
  },
  {
    id: "library-arroz-forno-legumes",
    title: "Arroz de forno com legumes",
    description: "Receita de aproveitamento com arroz, legumes e queijo.",
    ingredients: ["arroz", "cenoura", "milho", "ervilha", "queijo", "molho de tomate"],
    steps: [
      "Misture arroz cozido, legumes e molho de tomate.",
      "Ajuste o sal e transfira para um refratario.",
      "Cubra com queijo e leve ao forno até gratinar.",
    ],
    prepMinutes: 35,
    servings: 4,
    sourceLabel: "TudoGostoso",
    origin: "library",
  },
  {
    id: "library-frango-grelhado-limao",
    title: "Frango grelhado com limao",
    description: "Peito de frango marinado no limao com alho e ervas.",
    ingredients: ["frango", "limao", "alho", "azeite", "sal", "pimenta"],
    steps: [
      "Marine o frango com limao, alho, azeite, sal e pimenta por 20 minutos.",
      "Grelhe em frigideira quente até dourar dos dois lados.",
      "Descanse por 3 minutos antes de servir.",
    ],
    prepMinutes: 30,
    servings: 2,
    sourceLabel: "Panelinha",
    origin: "library",
  },
  {
    id: "library-bolo-banana-rapido",
    title: "Bolo de banana rapido",
    description: "Massa fofinha com banana e canela para cafe da tarde.",
    ingredients: ["banana", "ovo", "farinha de trigo", "acucar", "canela", "fermento"],
    steps: [
      "Amasse as bananas e misture com ovos e acucar.",
      "Acrescente farinha e canela até obter massa homogênea.",
      "Finalize com fermento e asse em forno medio por 35 minutos.",
    ],
    prepMinutes: 45,
    servings: 8,
    sourceLabel: "TudoGostoso",
    origin: "library",
  },
  {
    id: "library-sopa-abobora-gengibre",
    title: "Sopa de abobora com gengibre",
    description: "Cremosa, reconfortante e com toque levemente picante.",
    ingredients: ["abobora", "cebola", "alho", "gengibre", "sal", "azeite"],
    steps: [
      "Refogue cebola, alho e gengibre em azeite.",
      "Junte a abóbora em cubos, cubra com água e cozinhe até amaciar.",
      "Bata tudo, ajuste o sal e sirva quente.",
    ],
    prepMinutes: 40,
    servings: 4,
    sourceLabel: "Panelinha",
    origin: "library",
  },
];
