insert into public.recipes_br
  (slug, title, description, category, ingredients, steps, prep_minutes, servings, image_url, source_name, source_url, is_published, moderation_status, moderated_at)
values
  (
    'feijao-caseiro',
    'Feijão caseiro',
    'Feijão simples, bem temperado e com caldo encorpado para o dia a dia.',
    'principais',
    array['2 xícaras de feijão carioca', '1 folha de louro', '2 dentes de alho picados', '1/2 cebola picada', '1 colher de sopa de óleo', 'sal a gosto'],
    array['Deixe o feijão de molho por pelo menos 8 horas, se possível.', 'Escorra, coloque na panela de pressão com água nova e louro.', 'Cozinhe por cerca de 25 minutos após pegar pressão.', 'Refogue alho e cebola no óleo, junte parte do feijão e amasse para engrossar.', 'Misture tudo, ajuste o sal e ferva até o caldo ficar cremoso.'],
    55,
    6,
    'https://images.unsplash.com/photo-1515516969-d4008cc6241a?auto=format&fit=crop&w=1200&q=80',
    'TemAI Curadoria',
    null,
    true,
    'approved',
    now()
  ),
  (
    'arroz-branco',
    'Arroz branco soltinho',
    'Arroz básico, soltinho e perfeito para acompanhar qualquer refeição.',
    'principais',
    array['1 xícara de arroz', '2 xícaras de água quente', '1 dente de alho picado', '1 colher de sopa de óleo', 'sal a gosto'],
    array['Lave o arroz rapidamente e escorra bem.', 'Refogue o alho no óleo em fogo médio.', 'Adicione o arroz e mexa por 1 minuto.', 'Junte água quente e sal, abaixe o fogo e tampe parcialmente.', 'Cozinhe por 15 a 18 minutos, desligue e deixe descansar 5 minutos antes de soltar com garfo.'],
    22,
    3,
    'https://images.unsplash.com/photo-1536304993881-ff6e9eefa2a6?auto=format&fit=crop&w=1200&q=80',
    'TemAI Curadoria',
    null,
    true,
    'approved',
    now()
  ),
  (
    'macarrao-alho-e-oleo',
    'Macarrão alho e óleo',
    'Massa rápida, aromática e econômica para resolver a refeição.',
    'massas',
    array['250g de macarrão', '3 dentes de alho fatiados', '3 colheres de sopa de azeite', 'sal', 'pimenta-do-reino', 'salsinha opcional'],
    array['Cozinhe o macarrão em água salgada até ficar al dente.', 'Aqueça o azeite em fogo baixo e doure o alho sem queimar.', 'Misture o macarrão escorrido ao azeite com alho.', 'Ajuste sal, pimenta e finalize com salsinha.'],
    18,
    2,
    'https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=1200&q=80',
    'TemAI Curadoria',
    null,
    true,
    'approved',
    now()
  ),
  (
    'macarrao-molho-branco',
    'Macarrão ao molho branco',
    'Massa cremosa com molho branco simples e bem aveludado.',
    'massas',
    array['250g de macarrão', '1 colher de sopa de manteiga', '1 colher de sopa de farinha de trigo', '2 xícaras de leite', 'sal', 'noz-moscada', 'queijo ralado opcional'],
    array['Cozinhe o macarrão até ficar al dente.', 'Derreta a manteiga, adicione a farinha e mexa por 1 minuto.', 'Junte o leite aos poucos, mexendo até engrossar.', 'Tempere com sal e noz-moscada.', 'Misture o molho à massa e finalize com queijo se desejar.'],
    25,
    2,
    'https://images.unsplash.com/photo-1621996346565-e3dbc353d2e5?auto=format&fit=crop&w=1200&q=80',
    'TemAI Curadoria',
    null,
    true,
    'approved',
    now()
  ),
  (
    'macarrao-molho-de-queijo',
    'Macarrão ao molho de queijo',
    'Massa cremosa e reconfortante com molho de queijo fácil.',
    'massas',
    array['250g de macarrão', '1 xícara de leite', '1/2 xícara de creme de leite', '1 xícara de queijo ralado', '1 colher de manteiga', 'sal', 'pimenta-do-reino'],
    array['Cozinhe o macarrão em água salgada.', 'Aqueça leite, creme de leite e manteiga em fogo baixo.', 'Adicione o queijo aos poucos, mexendo até derreter.', 'Tempere e misture a massa ao molho.', 'Sirva imediatamente para manter a cremosidade.'],
    22,
    2,
    'https://images.unsplash.com/photo-1645112411341-6c4fd023714a?auto=format&fit=crop&w=1200&q=80',
    'TemAI Curadoria',
    null,
    true,
    'approved',
    now()
  ),
  (
    'pure-de-batata',
    'Purê de batata',
    'Purê cremoso, simples e clássico para acompanhar carnes e legumes.',
    'principais',
    array['4 batatas médias', '2 colheres de sopa de manteiga', '1/2 xícara de leite', 'sal', 'pimenta-do-reino'],
    array['Cozinhe as batatas descascadas em água com sal até ficarem macias.', 'Escorra e amasse ainda quentes.', 'Misture manteiga e leite aos poucos.', 'Mexa até ficar cremoso e ajuste sal e pimenta.'],
    30,
    4,
    'https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=1200&q=80',
    'TemAI Curadoria',
    null,
    true,
    'approved',
    now()
  ),
  (
    'frango-grelhado',
    'Frango grelhado',
    'Filé de frango suculento e bem dourado para refeições rápidas.',
    'principais',
    array['2 filés de frango', '1 dente de alho amassado', 'suco de 1/2 limão', 'sal', 'pimenta-do-reino', '1 colher de óleo ou azeite'],
    array['Tempere o frango com alho, limão, sal e pimenta.', 'Aqueça bem a frigideira com óleo.', 'Grelhe em fogo médio-alto até dourar de um lado.', 'Vire e cozinhe até o centro ficar opaco e suculento.', 'Deixe descansar 2 minutos antes de servir.'],
    20,
    2,
    'https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?auto=format&fit=crop&w=1200&q=80',
    'TemAI Curadoria',
    null,
    true,
    'approved',
    now()
  ),
  (
    'omelete-simples',
    'Omelete simples',
    'Omelete macia e prática para café da manhã, almoço leve ou jantar rápido.',
    'principais',
    array['2 ovos', '1 colher de sopa de leite ou água', 'sal', 'pimenta-do-reino', '1 colher de chá de manteiga', 'queijo ou ervas opcional'],
    array['Bata os ovos com leite, sal e pimenta.', 'Aqueça a manteiga em frigideira antiaderente.', 'Despeje os ovos e cozinhe em fogo baixo.', 'Quando firmar nas bordas, dobre a omelete.', 'Sirva ainda cremosa.'],
    10,
    1,
    'https://images.unsplash.com/photo-1510693206972-df098062cb71?auto=format&fit=crop&w=1200&q=80',
    'TemAI Curadoria',
    null,
    true,
    'approved',
    now()
  ),
  (
    'strogonoff-de-frango',
    'Strogonoff de frango',
    'Strogonoff cremoso, rápido e perfeito com arroz e batata palha.',
    'principais',
    array['500g de frango em cubos', '1/2 cebola picada', '1 colher de óleo', '2 colheres de ketchup', '1 colher de mostarda', '1 caixa de creme de leite', 'sal', 'pimenta-do-reino'],
    array['Refogue a cebola no óleo.', 'Adicione o frango e doure bem.', 'Tempere com sal e pimenta.', 'Junte ketchup e mostarda e misture.', 'Desligue o fogo, acrescente creme de leite e aqueça sem ferver.'],
    30,
    4,
    'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&w=1200&q=80',
    'TemAI Curadoria',
    null,
    true,
    'approved',
    now()
  ),
  (
    'panqueca-simples',
    'Panqueca simples',
    'Massa básica de panqueca para rechear com carne, frango, queijo ou legumes.',
    'massas',
    array['1 xícara de leite', '1 xícara de farinha de trigo', '1 ovo', '1 pitada de sal', '1 colher de óleo'],
    array['Bata leite, farinha, ovo, sal e óleo até ficar liso.', 'Aqueça uma frigideira antiaderente.', 'Espalhe uma concha fina de massa.', 'Doure dos dois lados e reserve.', 'Recheie e finalize com molho, se quiser.'],
    25,
    6,
    'https://images.unsplash.com/photo-1528207776546-365bb710ee93?auto=format&fit=crop&w=1200&q=80',
    'TemAI Curadoria',
    null,
    true,
    'approved',
    now()
  ),
  (
    'farofa-simples',
    'Farofa simples',
    'Farofa dourada e crocante para acompanhar churrasco, feijão ou almoço comum.',
    'principais',
    array['2 xícaras de farinha de mandioca', '2 colheres de sopa de manteiga', '1/2 cebola picada', 'sal', 'cheiro-verde opcional'],
    array['Derreta a manteiga em fogo médio.', 'Refogue a cebola até ficar transparente.', 'Adicione a farinha aos poucos, mexendo sempre.', 'Toste até ficar levemente dourada.', 'Ajuste sal e finalize com cheiro-verde.'],
    15,
    4,
    'https://images.unsplash.com/photo-1543352634-a1c51d9f1fa7?auto=format&fit=crop&w=1200&q=80',
    'TemAI Curadoria',
    null,
    true,
    'approved',
    now()
  ),
  (
    'bolo-simples',
    'Bolo simples',
    'Bolo caseiro fofinho para café da tarde.',
    'sobremesas',
    array['2 ovos', '1 xícara de açúcar', '2 colheres de sopa de manteiga', '1 xícara de leite', '2 xícaras de farinha de trigo', '1 colher de sopa de fermento'],
    array['Bata ovos, açúcar e manteiga até clarear.', 'Adicione leite e farinha aos poucos.', 'Misture o fermento delicadamente.', 'Despeje em forma untada.', 'Asse em forno preaquecido a 180 °C por 35 a 40 minutos.'],
    50,
    8,
    'https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=1200&q=80',
    'TemAI Curadoria',
    null,
    true,
    'approved',
    now()
  ),
  (
    'brigadeiro',
    'Brigadeiro',
    'Doce brasileiro clássico, cremoso e fácil de fazer.',
    'sobremesas',
    array['1 lata de leite condensado', '2 colheres de sopa de chocolate em pó', '1 colher de sopa de manteiga', 'chocolate granulado'],
    array['Misture leite condensado, chocolate e manteiga em uma panela.', 'Cozinhe em fogo baixo, mexendo sempre.', 'Quando desgrudar do fundo, desligue.', 'Espere esfriar, enrole e passe no granulado.'],
    25,
    20,
    'https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&w=1200&q=80',
    'TemAI Curadoria',
    null,
    true,
    'approved',
    now()
  ),
  (
    'cuscuz-simples',
    'Cuscuz simples',
    'Cuscuz de milho leve, rápido e ótimo com manteiga.',
    'lanches',
    array['1 xícara de flocão de milho', '1/2 xícara de água', 'sal', 'manteiga para servir'],
    array['Misture flocão, água e sal.', 'Deixe hidratar por 10 minutos.', 'Coloque na cuscuzeira com água no fundo.', 'Cozinhe no vapor por 10 a 12 minutos.', 'Sirva com manteiga.'],
    22,
    2,
    'https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=1200&q=80',
    'TemAI Curadoria',
    null,
    true,
    'approved',
    now()
  ),
  (
    'tapioca-simples',
    'Tapioca simples',
    'Tapioca rápida, macia e fácil de rechear.',
    'lanches',
    array['1/2 xícara de goma de tapioca hidratada', '1 pitada de sal', 'queijo, coco ou recheio de preferência'],
    array['Aqueça uma frigideira antiaderente.', 'Espalhe a goma formando uma camada uniforme.', 'Cozinhe até unir e soltar da frigideira.', 'Adicione o recheio, dobre e sirva.'],
    10,
    1,
    'https://images.unsplash.com/photo-1484723091739-30a097e8f929?auto=format&fit=crop&w=1200&q=80',
    'TemAI Curadoria',
    null,
    true,
    'approved',
    now()
  ),
  (
    'molho-de-tomate-caseiro',
    'Molho de tomate caseiro',
    'Molho simples, aromático e melhor que molho pronto.',
    'principais',
    array['6 tomates maduros', '1/2 cebola picada', '2 dentes de alho', '2 colheres de azeite', 'sal', 'manjericão opcional'],
    array['Pique os tomates ou bata rapidamente no liquidificador.', 'Refogue alho e cebola no azeite.', 'Adicione tomate e sal.', 'Cozinhe em fogo baixo por 25 a 30 minutos.', 'Finalize com manjericão.'],
    40,
    4,
    'https://images.unsplash.com/photo-1473093295043-cdd812d0e601?auto=format&fit=crop&w=1200&q=80',
    'TemAI Curadoria',
    null,
    true,
    'approved',
    now()
  ),
  (
    'carne-moida-refogada',
    'Carne moída refogada',
    'Carne moída simples, soltinha e bem temperada.',
    'principais',
    array['500g de carne moída', '1/2 cebola picada', '2 dentes de alho', '1 colher de óleo', 'sal', 'pimenta-do-reino', 'cheiro-verde opcional'],
    array['Aqueça o óleo e refogue cebola e alho.', 'Adicione a carne moída e mexa para soltar.', 'Cozinhe até secar a água e dourar levemente.', 'Tempere com sal e pimenta.', 'Finalize com cheiro-verde.'],
    25,
    4,
    'https://images.unsplash.com/photo-1529692236671-f1f6cf9683ba?auto=format&fit=crop&w=1200&q=80',
    'TemAI Curadoria',
    null,
    true,
    'approved',
    now()
  ),
  (
    'escondidinho-simples',
    'Escondidinho simples',
    'Escondidinho cremoso com purê e recheio salgado.',
    'principais',
    array['3 xícaras de purê de batata ou mandioca', '2 xícaras de carne moída ou frango desfiado', '1/2 xícara de queijo ralado', 'manteiga para untar'],
    array['Prepare o recheio bem temperado e reserve.', 'Espalhe metade do purê em um refratário untado.', 'Adicione o recheio e cubra com o restante do purê.', 'Finalize com queijo.', 'Leve ao forno a 200 °C por 20 minutos ou até gratinar.'],
    45,
    4,
    'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=1200&q=80',
    'TemAI Curadoria',
    null,
    true,
    'approved',
    now()
  ),
  (
    'fricasse-de-frango',
    'Fricassê de frango',
    'Frango cremoso com milho, queijo e batata palha.',
    'principais',
    array['2 xícaras de frango desfiado', '1 lata de milho', '1 caixa de creme de leite', '1/2 copo de requeijão', '1/2 cebola picada', 'queijo ralado', 'batata palha'],
    array['Refogue a cebola e misture o frango desfiado.', 'Bata milho, creme de leite e requeijão até formar um creme.', 'Misture o creme ao frango.', 'Coloque em um refratário, cubra com queijo e leve ao forno a 200 °C por 20 minutos.', 'Finalize com batata palha.'],
    40,
    4,
    'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?auto=format&fit=crop&w=1200&q=80',
    'TemAI Curadoria',
    null,
    true,
    'approved',
    now()
  ),
  (
    'lasanha-simples',
    'Lasanha simples',
    'Lasanha prática com molho, massa e queijo bem gratinado.',
    'massas',
    array['500g de massa de lasanha', '3 xícaras de molho de tomate', '300g de presunto ou frango', '300g de queijo muçarela', 'queijo ralado'],
    array['Espalhe molho no fundo do refratário.', 'Alterne camadas de massa, molho, recheio e queijo.', 'Finalize com molho e queijo ralado.', 'Cubra com papel alumínio e asse a 200 °C por 30 minutos.', 'Retire o papel e gratine por mais 10 minutos.'],
    55,
    6,
    'https://images.unsplash.com/photo-1619895092538-128341789043?auto=format&fit=crop&w=1200&q=80',
    'TemAI Curadoria',
    null,
    true,
    'approved',
    now()
  )
on conflict (slug) do update set
  title = excluded.title,
  description = excluded.description,
  category = excluded.category,
  ingredients = excluded.ingredients,
  steps = excluded.steps,
  prep_minutes = excluded.prep_minutes,
  servings = excluded.servings,
  image_url = excluded.image_url,
  source_name = excluded.source_name,
  source_url = excluded.source_url,
  is_published = true,
  moderation_status = 'approved',
  moderated_at = now(),
  updated_at = now();
